import numpy as np
import os
from NASA import *
Seq1='ATGGCGCACGTCCGAGGCTTGCAGCTGCCTGGCTGCCTGGCCCTGGCTGCCCTGTGTAGCCTTGTGCACAGCCAGCATGTGTTCCTGGCTCCTCAGCAAGCACGGTCGCTGCTCCAGCGG'
Seq2='ATGGCGCACGTCCGAGGCTTGCAGCTGCCTGGCTGCCTGGCCCTGGCTGCCCTGTGTAGCCTTGTGCACAGCCAGCATGTGTTCCTGGCTCCTCAGCAAGCACGGTCGCTGCTCCAGCGG'
MatchScore=1
PenaltyScore=0
RTB=30
AlignedSequence,AlignmentScore=CallNasa(MatchScore,PenaltyScore,RTB,Seq1,Seq2)
print(AlignedSequence[0])
print(AlignedSequence[1])
print(AlignmentScore)
